[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.120.4",
    "mcp>=1.20.0",
    "ollama>=0.6.1",
    "pydantic>=2.12.3",
    "ruff>=0.14.3",
    "uvicorn>=0.38.0",
]
